// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OnlineShop.Product.Grpc.Data;

#nullable disable

namespace OnlineShop.Product.Grpc.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20240322041801_TableCreationAndSeedData")]
    partial class TableCreationAndSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OnlineShop.Product.Grpc.Data.Entities.ProductEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Definition")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Definition = "Product1",
                            OrderId = 1
                        },
                        new
                        {
                            Id = 2,
                            Definition = "Product2",
                            OrderId = 1
                        },
                        new
                        {
                            Id = 3,
                            Definition = "Product3",
                            OrderId = 1
                        },
                        new
                        {
                            Id = 4,
                            Definition = "Product4",
                            OrderId = 2
                        },
                        new
                        {
                            Id = 5,
                            Definition = "Product5",
                            OrderId = 2
                        },
                        new
                        {
                            Id = 6,
                            Definition = "Product6",
                            OrderId = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
